//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UYCommerce.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UYCommerce.Resources.Views.Home.Index.en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartphones.
        /// </summary>
        internal static string Celulares {
            get {
                return ResourceManager.GetString("Celulares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers.
        /// </summary>
        internal static string Computadoras {
            get {
                return ResourceManager.GetString("Computadoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string Deporte {
            get {
                return ResourceManager.GetString("Deporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an e-commerce application where you can find all kinds of items and you will have the option to buy and create an account and much more.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        internal static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirts.
        /// </summary>
        internal static string Remeras {
            get {
                return ResourceManager.GetString("Remeras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        internal static string Ropa {
            get {
                return ResourceManager.GetString("Ropa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Tecnologia {
            get {
                return ResourceManager.GetString("Tecnologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        internal static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to UyCommerce an e-commerce app for selling products online.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
