//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UYCommerce.Resources.Views.Producto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VerProducto_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerProducto_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UYCommerce.Resources.Views.Producto.VerProducto.es", typeof(VerProducto_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar al carrito.
        /// </summary>
        internal static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add to cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntuación promedio.
        /// </summary>
        internal static string Average_rating {
            get {
                return ResourceManager.GetString("Average rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible.
        /// </summary>
        internal static string In_Stock {
            get {
                return ResourceManager.GetString("In Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay preguntas todavía..
        /// </summary>
        internal static string No_questions_yet_ {
            get {
                return ResourceManager.GetString("No questions yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay reviews..
        /// </summary>
        internal static string No_reviews_yet_ {
            get {
                return ResourceManager.GetString("No reviews yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Stock.
        /// </summary>
        internal static string Out_of_Stock {
            get {
                return ResourceManager.GetString("Out of Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad:.
        /// </summary>
        internal static string Quantity_ {
            get {
                return ResourceManager.GetString("Quantity:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos Relacionados.
        /// </summary>
        internal static string Similar_Products {
            get {
                return ResourceManager.GetString("Similar Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendidos.
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntar.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe tu pregunta.
        /// </summary>
        internal static string Write_a_question {
            get {
                return ResourceManager.GetString("Write a question", resourceCulture);
            }
        }
    }
}
